id: IF3968329
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-4952
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 12:40:36.404225+00:00
last_modified: 2023-09-26 12:40:36.404233+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15822
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15822
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་རྩ་འགྲེལ་ཆེན་མོ། ༼གློག་ཀླད་པར་མ།༽
  languages:
  - bo
  author: རྒྱལ་ཚབ་དར་མ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9710848181202045
  ocr_word_median_confidence_index: 1.0
bases:
  I1KG15824:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15824
      total_pages: 634
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15824.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9710848181202045
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
